server:
  port: 9090
  servlet:
    context-path: /makhir/api

spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
    platform: h2
    #schema: classpath*:schema.sql
    #data: classpath*:data.sql
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        use_sql_comments: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    
logging:
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level %thread{5} [%logger{15}] - %msg%n'
  level:
    root: info
    org:
      h2: debug
      hibernate:
        sql: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
    com:
      makhir:
        springboot:
          redis: debug
          