DROP SEQUENCE IF EXISTS ID_SEQ;
DROP TABLE IF EXISTS CUSTOMER;

CREATE SEQUENCE ID_SEQ;

CREATE TABLE IF NOT EXISTS CUSTOMER (
  ID BIGINT default ID_SEQ.NEXTVAL PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  GENDER VARCHAR(6) NOT NULL,
  CONTACT VARCHAR(20) NOT NULL,
  EMAIL VARCHAR(30) NOT NULL
);